import { JobImage } from "@/interfaces";

export const ImagenesJobs: JobImage[] = [
  {
    src: "/images/jobs/modatex01.jpeg",
    alt: "modatex01",
    id: "modatex",
    type: "mobile",
  },
  {
    src: "/images/jobs/modatex02.jpeg",
    alt: "modatex02",
    id: "modatex",
    type: "mobile",
  },
  {
    src: "/images/jobs/modatex03.jpeg",
    alt: "modatex03",
    id: "modatex",
    type: "mobile",
  },
  {
    src: "/images/jobs/modatex04.jpeg",
    alt: "modatex04",
    id: "modatex",
    type: "mobile",
  },
  {
    src: "/images/jobs/bluerabbit01.png",
    alt: "bluerabbit01",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit02.png",
    alt: "bluerabbit02",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit03.png",
    alt: "bluerabbit03",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit04.png",
    alt: "bluerabbit04",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit05.png",
    alt: "bluerabbit05",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit06.png",
    alt: "bluerabbit06",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit07.png",
    alt: "bluerabbit07",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit08.png",
    alt: "bluerabbit08",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit09.png",
    alt: "bluerabbit09",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit10.png",
    alt: "bluerabbit10",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit11.png",
    alt: "bluerabbit11",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit12.png",
    alt: "bluerabbit12",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit13.png",
    alt: "bluerabbit13",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/bluerabbit14.png",
    alt: "bluerabbit14",
    id: "bluerabbit",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe1.png",
    alt: "homedeluxe1",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe2.png",
    alt: "homedeluxe2",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe3.png",
    alt: "homedeluxe3",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe4.png",
    alt: "homedeluxe4",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe5.png",
    alt: "homedeluxe5",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe6.png",
    alt: "homedeluxe6",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe7.png",
    alt: "homedeluxe7",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe8.jpeg",
    alt: "homedeluxe8",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/homedeluxe9.jpeg",
    alt: "homedeluxe9",
    id: "homedeluxe",
    type: "web",
  },
  {
    src: "/images/jobs/MyTineraryNative.png",
    alt: "MyTineraryNative",
    id: "mytinerary",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-12.png",
    alt: "techforb-0",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-1.png",
    alt: "techforb-1",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-2.png",
    alt: "techforb-2",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-3.png",
    alt: "techforb-3",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-4.png",
    alt: "techforb-4",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-5.png",
    alt: "techforb-5",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-6.png",
    alt: "techforb-6",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-7.png",
    alt: "techforb-7",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-8.png",
    alt: "techforb-8",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-9.png",
    alt: "techforb-9",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-10.png",
    alt: "techforb-10",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/techforb-11.png",
    alt: "techforb-11",
    id: "techforb",
    type: "mobile",
  },
  {
    src: "/images/jobs/touken1.png",
    alt: "touken1",
    id: "touken",
    type: "web",
  },
  {
    src: "/images/jobs/touken2.png",
    alt: "touken2",
    id: "touken",
    type: "web",
  },
  {
    src: "/images/jobs/touken3.png",
    alt: "touken3",
    id: "touken",
    type: "web",
  },
  {
    src: "/images/jobs/touken4.png",
    alt: "touken4",
    id: "touken",
    type: "web",
  },
  {
    src: "/images/jobs/touken5.png",
    alt: "touken5",
    id: "touken",
    type: "web",
  },
  {
    src: "/images/jobs/touken6.png",
    alt: "touken6",
    id: "touken",
    type: "web",
  },
  {
    src: "/images/jobs/touken7.png",
    alt: "touken7",
    id: "touken",
    type: "web",
  },
  {
    src: "/images/jobs/toukenMobile1.png",
    alt: "toukenMobile1",
    id: "touken",
    type: "mobile",
  },
  {
    src: "/images/jobs/toukenMobile2.png",
    alt: "toukenMobile2",
    id: "touken",
    type: "mobile",
  },
  {
    src: "/images/jobs/toukenMobile3.png",
    alt: "toukenMobile3",
    id: "touken",
    type: "mobile",
  },
  {
    src: "/images/jobs/toukenMobile4.png",
    alt: "toukenMobile4",
    id: "touken",
    type: "mobile",
  },
  {
    src: "/images/jobs/toukenMobile5.png",
    alt: "toukenMobile5",
    id: "touken",
    type: "mobile",
  },
  {
    src: "/images/jobs/toukenMobile6.png",
    alt: "toukenMobile6",
    id: "touken",
    type: "mobile",
  },
  {
    src: "/images/jobs/toukenMobile7.png",
    alt: "toukenMobile7",
    id: "touken",
    type: "mobile",
  },
  {
    src: "/images/jobs/touken-mobile.jpg",
    alt: "touken-mobile",
    id: "touken",
    type: "mobile",
  },
  {
    src: "/images/jobs/administracion01.jpeg",
    alt: "administracion Rolon",
    id: "adminrolon",
    type: "web",
  },
  {
    src: "/images/jobs/administracion02.jpeg",
    alt: "administracion Rolon",
    id: "adminrolon",
    type: "web",
  },
  {
    src: "/images/jobs/administracion03.jpeg",
    alt: "administracion Rolon",
    id: "adminrolon",
    type: "web",
  },
  {
    src: "/images/jobs/administracion04.jpeg",
    alt: "administracion Rolon",
    id: "adminrolon",
    type: "web",
  },
];
